services:
  web:
    build:
      context: ../../../
      dockerfile: ./env/local/docker/Dockerfile
    command: "uvicorn src.__init__:app --host 0.0.0.0 --port 8000 --reload"
    container_name: web
    depends_on:
      alembic:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    env_file:
      - ../../../local.env
    ports:
      - 8000:8000
    volumes:
      - ../../../:/project
    profiles: [backend]
  alembic:
    build:
      context: ../../../
      dockerfile: ./env/local/docker/Dockerfile
    command: "alembic upgrade heads"
    container_name: alembic
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../../../local.env
    volumes:
      - ../../../:/project
    profiles: [backend]
  db:
    image: postgres:15
    container_name: postgres
    env_file:
      - ../../../local.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data-playground:/var/lib/postgresql/data

volumes:
  postgres-data-playground:
